services:
  libguestfs-tools:
    image: ghcr.io/stackopshq/libguestfs-tools:latest
    container_name: libguestfs-tools
    privileged: true
    volumes:
      - ./images:/workspace/images:Z
      - ./shared:/workspace/shared:Z
    environment:
      - LIBGUESTFS_BACKEND=direct
      - LIBGUESTFS_DEBUG=0
      - LIBGUESTFS_TRACE=0
      - LIBGUESTFS_PROGRESS=1
      - LIBGUESTFS_VERBOSE=0
      - LIBGUESTFS_MEMSIZE=4096
      - LIBGUESTFS_SMP=4
    stdin_open: true
    tty: true
    working_dir: /workspace
